name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select -p
      - run: sudo xcode-select -switch /Applications/Xcode_16.app
      - run: swift test